create type public.game_state as enum ('waiting', 'started', 'ended');
create table public.games (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    players text [] not null,
    guesses jsonb [] not null,
    state public.game_state not null default 'waiting'::"game_state",
    constraint games_pkey primary key (id)
) tablespace pg_default;
