create table "public"."guesses" (
    "id" bigint generated by default as identity not null,
    "game_id" bigint,
    "user_id" uuid not null default gen_random_uuid(),
    "guess" text[] not null default '{}'::text[]
);


alter table "public"."guesses" enable row level security;

alter table "public"."games" drop column "player_one_guesses";

alter table "public"."games" drop column "player_one_name";

alter table "public"."games" drop column "player_two_guesses";

alter table "public"."games" drop column "player_two_name";

CREATE UNIQUE INDEX game_players_pkey ON public.guesses USING btree (id);

alter table "public"."guesses" add constraint "game_players_pkey" PRIMARY KEY using index "game_players_pkey";

alter table "public"."guesses" add constraint "game_players_game_id_fkey" FOREIGN KEY (game_id) REFERENCES games(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."guesses" validate constraint "game_players_game_id_fkey";

alter table "public"."guesses" add constraint "game_players_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."guesses" validate constraint "game_players_user_id_fkey";

grant delete on table "public"."guesses" to "anon";

grant insert on table "public"."guesses" to "anon";

grant references on table "public"."guesses" to "anon";

grant select on table "public"."guesses" to "anon";

grant trigger on table "public"."guesses" to "anon";

grant truncate on table "public"."guesses" to "anon";

grant update on table "public"."guesses" to "anon";

grant delete on table "public"."guesses" to "authenticated";

grant insert on table "public"."guesses" to "authenticated";

grant references on table "public"."guesses" to "authenticated";

grant select on table "public"."guesses" to "authenticated";

grant trigger on table "public"."guesses" to "authenticated";

grant truncate on table "public"."guesses" to "authenticated";

grant update on table "public"."guesses" to "authenticated";

grant delete on table "public"."guesses" to "service_role";

grant insert on table "public"."guesses" to "service_role";

grant references on table "public"."guesses" to "service_role";

grant select on table "public"."guesses" to "service_role";

grant trigger on table "public"."guesses" to "service_role";

grant truncate on table "public"."guesses" to "service_role";

grant update on table "public"."guesses" to "service_role";


